@startuml ess
    entity User {
        * id_user : VARCHAR
        --
        * username : VARCHAR
        * email : VARCHAR
        * password : VARCHAR
        * status : enum
    }
    entity Role {
        * id_role : VARCHAR
        --
        * role_type : VARCHAR
    }
    entity OurCompany {
        nama_company : VARCHAR
        alamat_company : VARCHAR
        contact : VARCHAR
        lattitude :  VARCHAR
        longitude : VARCHAR
        logo : VARCHAR
    }
    entity Employe {
        * id_employee : VARCHAR
        --
        * id_user : VARCHAR
        * NIK : INT
        * nama : VARCHAR
        * tempat_lahir : VARCHAR
        * tanggal_lahir : DATE
        * alamat_ktp : VARCHAR
        * pendidikan_terakhir : VARCHAR
        * nama_pendidikan_terakhir : VARCHAR
        * jurusan_pendidikan_terakhir : VARCHAR
        * alamat_email_aktif : VARCHAR
        * no_tlp_aktif : VARCHAR
        * kontak_darurat : VARCHAR
    }
     entity EmployeSecondaryData {
        * id_employe_secondary : VARCHAR
        --
        * id_employee
        no_npwp : VARCHAR
        no_kartu_keluarga : VARCHAR
        status_saat_ini : enum
        tanggungan : INT
        no_rek : VARCHAR
        nama_rek : VARCHAR
        no_bpjs_kesehatan : VARCHAR
        status_bpjs_kesehatan : enum
        status_bpjs_ketenaga_kerjaan : enum
        created_at : DATE
        updated_at : DATE
    }
    entity EmployeeFile {
        * id_employee_file : VARCHAR
        --
        * id_employee : VARCHAR
        file_bpjs_kesehatan : VARCHAR
        file_bpjs_ketenagakerjaan : VARCHAR
        file_npwp : VARCHAR
        * file_kartu_keluarga : VARCHAR
        * file_ijazah : VARCHAR
        file_sertifikat_keahlian : VARCHAR
        file_ktp : VARCHAR
        created_at : DATE
        updated_at : DATE
    }
    entity Position {
        * id_position : VARCHAR
        --
        * position_name : VARCHAR
    }
    entity EmployeePosition{
        * id_employee_position : VARCHAR
        --
        * id_position : VARCHAR
        * id_employee : VARCHAR
    }
    entity EmployeeMember {
        * id_employee_lead: VARCHAR
        * id_employee_direct_sub : VARCHAR
    }
    entity CurrentLeave {
        * id_employee : VARCHAR
        --
        * current_leave : float
    }
    entity Client {
        * id_client : VARCHAR
        --
        * nama_client : VARCHAR
        * lattitude :  VARCHAR
        * longitude : VARCHAR
    }
    entity Project {
        * id_project : VARCHAR
        -- 
        * id_client : VARCHAR
        * project_name : VARCHAR
    }
    entity EmployeOnProject {
        * id_employe_on_project : VARCHAR
        --
        * id_employee : VARCHAR
        * id_project : VARCHAR
        created_at : VARCHAR
        updated_at : VARCHAR
    }
    entity AbsenConfiguration {
        * minimal_masuk_jam_kerja : TIME(HH:MI)
        * maksimal_masuk_jam_kerja : TIME(HH:MI)
        * durasi_jam_kerja : INT
        * interval_keterlambatan : INT
        * bobot_keterlambatan : float
        * maksimal_bobot_keterlambatan : FLOAT
        * pic_absensi : id_employee
    }
    entity Absensi {
        * id_absensi : VARCHAR
        --
        * id_employee : VARCHAR
        id_leave : VARCHAR
        * tanggal_absen
        * absen_pagi : TIME
        * absen_pulang : TIME
        terlambat_kerja : INT
        bobot : float
        over_time : INT
        keterangan : TEXT
    }
    entity Approval {
        * id_approval : VARCHAR
        --
        feature_type : enum
        whos_approv : VARCHAR
        status_approv : VARCHAR
        feature_id : VARCHAR
        crated_at : timestamps
        updated_at : timestamps
        keterangan : TEXT
    }
    entity Notes {
        * id_notes : VARCHAR
        --
        * id_employee : VARCHAR
        * feature_id : VARCHAR
        feature_type : VARCHAR
        created_at : timestamps
    }
    
    entity TimesheetConfiguration {
        * batas_pengeditan_timesheet : INT
        * PIC_timesheet : VARCHAR
    }
    entity Timesheet{
        * id_timesheet : VARCHAR
        --
        * id_employee : VARCHAR
        * id_employee_position : VARCHAR
        * id_activity : VARCHAR
        * id_project : VARCHAR
        * crated_at : DATE
        updated_at : Date
        * is_holiday : enum
    }
    entity ActivityTimesheet {
        * id_activity : VARCHAR
        --
        * name_activity : VARCHAR
    }
    entity TimesheetDetail {
        * id_detail_timesheet : VARCHAR
        --
        * id_timesheet : VARCHAR
        * created_at : Time
        * updated_at : Time
        * work_description : VARCHAR
        * break_hours : TIME
        * total_hours : float
        * over_time_hours : float
        * regular_hours : float
    }
    entity CutiConfiguration {
        * status_reset_cuti
        * bulan_reset_cuti
        * factor_reset_cuti
        * maksimal_cuti_perbulan
        * PIC_cuti
    }
    entity CutiType {
        * id_leave_type : VARCHAR
        --
        * cuti_type_name : VARCHAR
        * potongan_cuti : FLOAT
        * ditujukan : ENUM
    }
    entity Cuti {
        * id_cuti : VARCHAR
        --
        * id_employee : VARCHAR
        tanggal_penerbitan_form : DATE
        dari_tanggal : DATE
        keterangan_cuty : TEXT
        no_tlp : VARCHAR
        alamat_selama_cuty : VARCHAR
        jenis_cuty : enum
        total_hari : INT
        * sedang_di_project : enum
        tugas_yang_diserahkan : VARCHAR
        pegawai_pengganti : VARCHAR
        catatan : TEXT
        issu_by : TEXT
        leave_type : enum
        status_approval : enum
    }

    ' entity Reimburstment {
    '     * id_reimburstment : VARCHAR
    '     --
    '     * id_employee : VARCHAR
    '     * no_vourcher : VARCHAR
    '     * remburstment_payment_type : enunm
    '     Bank : VARCHAR
    '     name_bank : VARCHAR
    '     account_no : VARCHAR
    '     bank_branch : VARCHAR
    '     struck_reimburstment : VARCHAR
    '      * transaction_date : DATE
    '     * account_code : VARCHAR
    '     * description : TEXT
    '     * total_amount : INT
    '     notes : TEXT
    ' }

    ' entity StatusApprovReimburstment {
    '     * id_status_reimburstment : VARCHAR
    '     --
    '     * status_approv_lead : enum
    '     * date_approval_lead : DATE
    '     * approval_for_coo : enum
    '     status_approval_coo : enum
    '     date_approval_coo : DATE
    '     * status_approval_hr : enum
    '     * date_approval_hr : DATE
    '     * status_approval_finance : enum
    '     * date_approval_finance : DATE
    '     * status_receipt : enum
    '     * date_receipt : DATE
    ' }

    


User ||--|| Employe :  Employee Account
User ||--|| Role : user role
Employe ||--|| EmployeSecondaryData : Employee secondary data
Employe ||--|| EmployeeFile : EmployeeFile
Position ||--o{ EmployeePosition : Employe Position
Employe ||--|| EmployeePosition : EmployeePosition Lead
EmployeePosition }o--o{ EmployeeMember : Employee Member
Employe ||--o{ Absensi : absen employee
Client ||--o{ Project : Client project
Project ||--o{ EmployeOnProject : project handled
Employe ||-o{ EmployeOnProject : Employee handle projects
EmployeePosition ||--|{ Approval : PIC approval
EmployeePosition ||--|| AbsenConfiguration : PIC configuration untuk absensi
Absensi ||--|{ Approval : Absensi Approval
Employe ||--o{ Notes : Employee create notes
Absensi ||--o{ Notes : notes absensi
Employe ||--|| CurrentLeave : Sisa jatah cuti employee
Employe ||--o{ Cuti : Employee mengajukan Cuti
Cuti ||--o{ Absensi : absensi cuti
EmployeePosition ||--|| TimesheetConfiguration : Timeshete PIC and configuration
Timesheet ||--o{ TimesheetDetail : Timesheet detail
ActivityTimesheet ||--|{ TimesheetDetail : Acitivity Timesheet
Timesheet ||--o{ Approval : Approval for timesheet
Timesheet ||--o{ Notes : Notes for timesheet
TimesheetDetail ||--o{ Notes : Notes for timesheet detail
EmployeePosition ||--|| CutiConfiguration : PIC cuti
Employe ||--|{ Timesheet : Employee Timesheet
' Employe ||--|{ Timesheet : Employee Timesheet
' ActivityTimesheet ||--|{ TimesheetDetail : Timesheet Activity
' Project ||--|{ TimesheetDetail : Project in timesheet
' Timesheet ||--|{ TimesheetDetail : Detail Timesheet
' Employe ||--|{ Reimburstment : submit reimbursment
' Reimburstment ||--|{ StatusApprovReimburstment : Approval Reimburstment

@enduml